name: weather_mockon
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # http package
  http: ^1.4.0

  #cache
  shared_preferences: ^2.5.3

  #stocker en local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
